[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

[profile.optimizer] 
number-of-optimizations = 200


[fmt]
line_length = 80


[invariant]
runs = 2000
depth = 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true